# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build package using PyInstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows-amd64:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9 amd64
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Package application
      env: 
        KIVY_GL_BACKEND: angle_sdl2
      run: poetry run build-onefile

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sega-slider-windows-amd64
        path: dist/*


  build-windows-x86:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9 x86
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x86

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: poetry install --dev

    - name: Package application
      env: 
        KIVY_GL_BACKEND: angle_sdl2
      run: poetry run build-onefile

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sega-slider-windows-x86
        path: dist/*
